#配置数据库的连接信息
spring:
  application:
    name: tilas-web-management
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tilas
    #      driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234

#mybatis 的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    驼峰命名映射开关：开启
#    要求：xxx_abc -> xxxAbc
    map-underscore-to-camel-case: true

# Deleted:      #mybatis 的相关配置
# Deleted:      mybatis:
# Deleted:        configuration:
# Deleted:          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

